### ISSUE TITLE
getaddrinfo ENOT FOUND

### ISSUE THREAD

**Issue by Destrocamil** [iam4x/bobarr#148]
Been unable to add any movie to my library. Firstly, it says "getaddrinfo ENOT FOUND" then "duplicate key value violates unique constraint "UQ_e67ea82f6973f5b9a6747fba346".
So, from what I understand, it faces problems to connect to Redis but somehow something is stored in the DB.
Transmission does not start any download.

And one note more: can't Dowload Tv shows, appears like a "forbiden" sign on the "Download" button.

Let me know if I can help

EDIT:
more info

bobarr-api          | 2020-09-01 03:09:08.660 [info] LibraryService - track movie - {"tmdbId":338762}
bobarr-api          | 2020-09-01 03:09:08.691 [info] JobsService - add download movie job - {"movieId":8}
bobarr-api          | 2020-09-01 03:09:08.693 [error] ExceptionsHandler - getaddrinfo ENOTFOUND redis - {"trace":"Error: getaddrinfo ENOTFOUND redis\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}

and then that error persist

bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
bobarr-api          | [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
bobarr-api          | [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
bobarr-api          | [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
bobarr-api          | [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
bobarr-api          | [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
bobarr-api          | [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
bobarr-api          | [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

If I try to add the movie again:
bobarr-api          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
bobarr-api          | 2020-09-01 03:10:29.888 [error] ExceptionsHandler - duplicate key value violates unique constraint "UQ_e67ea82f6973f5b9a6747fba346" - {"trace":"QueryFailedError: duplicate key value violates unique constraint \"UQ_e67ea82f6973f5b9a6747fba346\"\n    at new QueryFailedError (/usr/src/app/node_modules/typeorm/error/QueryFailedError.js:11:28)\n    at Query.<anonymous> (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)\n    at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:139:19)\n    at Client._handleErrorMessage (/usr/src/app/node_modules/pg/lib/client.js:326:17)\n    at Connection.emit (events.js:315:20)\n    at /usr/src/app/node_modules/pg/lib/connection.js:109:12\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)"}

**Comment by iam4x** [comment]
Can you run `docker-compose ps` and send me the output? Also if you can pm me on Discord I can help.

**Comment by qqnc** [comment]
It happens to me, any idea of root cause?

**Comment by iam4x** [comment]
Yes the bitnami image is not arm compatible I guess that's why.

**Comment by bwt615** [comment]
> Yes the bitnami image is not arm compatible I guess that's why.

Would you mind explaining how to make this swap?
