### ISSUE TITLE
can't parse movie name or year

### ISSUE THREAD

**Issue by cedjo** [iam4x/bobarr#157]
Error: cant parse movie name or year
    at Object.<anonymous> (/usr/src/app/dist/modules/jobs/processors/scan-library.processor.js:189:23)
    at Object.exports.forEachSeries (/usr/src/app/node_modules/p-iteration/lib/static-methods.js:34:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ScanLibraryProcessor.scanMoviesFolder (/usr/src/app/dist/modules/jobs/processors/scan-library.processor.js:185:9)

impossible to scan library, mount point is at /volume1/Movies, movies folder=Parents, shows folder=Series

**Comment by iam4x** [comment]
Do you know on what file it is failing ?
