### ISSUE TITLE
download immediately fails

### ISSUE THREAD

**Issue by sivvo** [iam4x/bobarr#181]
all download fail immediately.

In bobarr it just gives the "searching" icon indefinitely.
In jackett jobs I get an immediate entry in failed

```
#57
    Added at
    20:03:09
    less than 5 seconds
    Process started at
    20:03:09
    less than 5 seconds
    Failed at
    20:03:09

download_movieattempt #2

TypeError: Cannot read property 'indexer' of undefined
    at JackettService.getConfiguredIndexers (/usr/src/app/dist/modules/jackett/jackett.service.js:81:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async JackettService.search (/usr/src/app/dist/modules/jackett/jackett.service.js:152:26)
    at async DownloadProcessor.downloadMovie (/usr/src/app/dist/modules/jobs/processors/download.processor.js:51:30)
```
I previously had a working instance running in a VM under vmware. I moved it to a new VM (full copy of the docker-compose directory, including the library and packages. I did a full install of bobarr via the script, and then replaced the directory with the full backup. I can't see anything amiss locally on the file system though

**Comment by sivvo** [comment]
re-entering the jackett token seems to have sprung it back into life!
