### ISSUE TITLE
Magnet error

### ISSUE THREAD

**Issue by Plnda** [iam4x/bobarr#56]
Im getting the following error when im trying to download something.

`Unsupported protocol magnet:
Error: Unsupported protocol magnet:
    at RedirectableRequest._performRequest (/usr/src/app/node_modules/follow-redirects/index.js:156:24)
    at RedirectableRequest._processResponse (/usr/src/app/node_modules/follow-redirects/index.js:260:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/src/app/node_modules/follow-redirects/index.js:50:10)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:476:22)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)`

**Comment by iam4x** [comment]
Hi @Plnda, this is definitely a bug. 

Could you send me what torrent website are your using in jackett and what movie/tvshow you tried to download?

**Comment by Plnda** [comment]
The following trackers are being used

`1337x Public	
KickAssTorrent (kat.li) Public	
KickAssTorrent Public	
RARBG Public	
`

**Comment by Plnda** [comment]
im also seeing this in my dashboard

```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at dispatchHttpRequest (/usr/src/app/node_modules/axios/lib/adapters/http.js:57:22)
    at new Promise (<anonymous>)
    at httpAdapter (/usr/src/app/node_modules/axios/lib/adapters/http.js:18:10)
    at dispatchRequest (/usr/src/app/node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async TransmissionService.addTorrentURL (/usr/src/app/dist/modules/transmission/transmission.service.js:46:26)
```

**Comment by iam4x** [comment]
Thank your for the details, I could improve as well the multi indexer search it should be much faster to find a result to download.

The issue should be fixed 👍

**Comment by iam4x** [comment]
I've found another case where it could happen after a redirection
